# Generated by Django 4.2.2 on 2023-10-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surplusapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='description',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='sourceinfo',
            name='ratings',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
