# Generated by Django 4.2.2 on 2023-10-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surplusapp', '0002_listings_description_sourceinfo_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
