# Generated by Django 4.2.2 on 2023-10-13 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surplusapp', '0003_alter_listings_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='surplusapp.sourceinfo'),
        ),
    ]
